#!/usr/bin/env bash

alias gst='git status'
alias gl='git log --oneline --cherry'
alias gll='git log --graph --cherry --pretty=format:"%h <%an> %ar %s"'
alias gp='git push'
alias gpl='git pull'
alias gcf='git config -l'
alias gaa='git add .'
alias gcf='git config --list'
alias gba='git branch -a'
alias gbd='git branch --delete'
alias gbrn='git branch -m'
alias gho='git hash-object'
alias gcat='git cat-file'
alias gs='git switch'
alias gsl='git shortlog'
alias gdf='git difftool'
alias gca='git commit -am'
alias gc='git commit -m'